"""create records table

Revision ID: 4bb810ae657f
Revises: 
Create Date: 2026-03-22 20:02:47.394509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb810ae657f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethanol', sa.Float(), nullable=False),
    sa.Column('glucose', sa.Float(), nullable=False),
    sa.Column('fructose', sa.Float(), nullable=False),
    sa.Column('titratable_acidity', sa.Float(), nullable=False),
    sa.Column('volatile_acids', sa.Float(), nullable=False),
    sa.Column('malic_acid', sa.Float(), nullable=False),
    sa.Column('tartaric_acid', sa.Float(), nullable=False),
    sa.Column('lactic_acid', sa.Float(), nullable=False),
    sa.Column('ph', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('must_weight_brix', sa.Float(), nullable=False),
    sa.Column('extract', sa.Float(), nullable=False),
    sa.Column('glycerol', sa.Float(), nullable=False),
    sa.Column('yeast_assimilable_nitrogen', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
